# Generated by Django 4.1 on 2022-08-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("committees", "0001_initial"),
        ("initiatives", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField(blank=True, null=True)),
                ("modified_date", models.DateTimeField()),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("filename", models.CharField(max_length=200)),
                ("document_id", models.CharField(max_length=100)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_original", models.BooleanField()),
                ("date", models.DateTimeField()),
                ("language", models.CharField(max_length=5)),
                ("size", models.BigIntegerField(blank=True, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("index", models.CharField(blank=True, max_length=100, null=True)),
                ("take_the_original", models.BooleanField(blank=True, null=True)),
                ("published", models.BooleanField(blank=True, null=True)),
                ("ers_file_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttachmentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=500)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("reference", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("group_id", models.IntegerField()),
                ("modified_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("decide_send_date", models.DateTimeField(blank=True, null=True)),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("planned_start_date", models.DateTimeField(blank=True, null=True)),
                ("translation_date", models.DateTimeField(blank=True, null=True)),
                ("adoption_date", models.DateTimeField(blank=True, null=True)),
                ("is_current", models.BooleanField()),
                (
                    "target_groups",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                (
                    "consultation_objective",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("created_date", models.DateTimeField()),
                ("total_feedback", models.IntegerField()),
                ("planned_end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "planned_period",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("feedback_period", models.IntegerField()),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "author_surname",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "author_mail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "author_phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "survey_contact_mail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_complete", models.BooleanField()),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True, to="publication_documents.attachment"
                    ),
                ),
                (
                    "front_end_stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publication_front_end",
                        to="initiatives.stage",
                    ),
                ),
                (
                    "initiative_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.status",
                    ),
                ),
                (
                    "receiving_feedback_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_feedback",
                        to="initiatives.status",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.stage",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.type",
                    ),
                ),
                (
                    "useful_links",
                    models.ManyToManyField(to="publication_documents.link"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attachment",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publication_documents.attachmenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="work_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committees.workgroup",
            ),
        ),
        migrations.AddField(
            model_name="attachment",
            name="work_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="initiatives.type"
            ),
        ),
    ]
