# Generated by Django 4.1 on 2022-08-21 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("initiatives", "0001_initial"),
        ("categories", "0001_initial"),
        ("committees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField()),
                ("modified_date", models.DateTimeField()),
                ("reference", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=1000)),
                ("filename", models.CharField(max_length=200)),
                ("document_id", models.CharField(max_length=100)),
                ("registration_number", models.CharField(max_length=100)),
                ("is_original", models.BooleanField()),
                ("date", models.DateTimeField()),
                ("language", models.CharField(max_length=5)),
                ("size", models.BigIntegerField()),
                ("pages", models.IntegerField()),
                ("type", models.CharField(max_length=100)),
                ("index", models.CharField(max_length=100)),
                ("take_the_original", models.BooleanField()),
                ("published", models.BooleanField()),
                ("ers_file_name", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="categories.category",
                    ),
                ),
                (
                    "work_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committees.workgroup",
                    ),
                ),
                (
                    "work_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("reference", models.CharField(max_length=100)),
                ("reference_number", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=1000)),
                ("group_id", models.IntegerField()),
                ("modified_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("decide_send_date", models.DateTimeField()),
                ("published_date", models.DateTimeField()),
                ("planned_start_date", models.DateTimeField(blank=True, null=True)),
                ("translation_date", models.DateTimeField(blank=True, null=True)),
                ("adoption_date", models.DateTimeField()),
                ("is_current", models.BooleanField()),
                (
                    "consultation_objective",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_date", models.DateTimeField()),
                ("total_feedback", models.IntegerField()),
                ("planned_end_date", models.DateTimeField(blank=True, null=True)),
                ("planned_period", models.CharField(max_length=100)),
                ("front_end_stage", models.CharField(max_length=100)),
                ("feedback_period", models.IntegerField()),
                ("author_name", models.CharField(max_length=100)),
                ("author_surname", models.CharField(max_length=100)),
                ("author_mail", models.CharField(max_length=100)),
                ("author_phone_number", models.CharField(max_length=100)),
                (
                    "survey_contact_mail",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("is_complete", models.BooleanField()),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publication_documents.attachment",
                    ),
                ),
                (
                    "initiative_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.status",
                    ),
                ),
                (
                    "receiving_feedback_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiving_feedback",
                        to="initiatives.status",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.stage",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.type",
                    ),
                ),
                (
                    "useful_links",
                    models.ManyToManyField(to="publication_documents.link"),
                ),
            ],
        ),
    ]
