# Generated by Django 4.1 on 2022-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication_documents", "0002_alter_attachment_work_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
