# Generated by Django 4.1 on 2022-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication_documents", "0003_alter_attachment_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="title",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
    ]
