# Generated by Django 4.1 on 2022-08-26 16:47

import publication_documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication_documents", "0004_alter_attachment_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="sentiment_map",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="sentiment_maps/png/",
            ),
        ),
    ]
