# Generated by Django 4.1 on 2022-08-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publication_documents", "0005_publication_sentiment_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="sentiment_map_html",
            field=models.FileField(
                blank=True, null=True, upload_to="sentiment_maps/html/"
            ),
        ),
    ]
