# Generated by Django 4.1 on 2022-08-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("publication_documents", "0006_publication_sentiment_map_html"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="sentiment_map",
            new_name="sentiment_map_png",
        ),
    ]
