# Generated by Django 4.1 on 2022-08-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("initiatives", "0001_initial"),
        ("feedbacks", "0001_initial"),
        ("committees", "0001_initial"),
        ("publication_documents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="publication_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="publication_documents.publication",
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="initiatives.status"
            ),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="committees.usertype",
            ),
        ),
    ]
