# Generated by Django 4.1 on 2022-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="tr_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
