# Generated by Django 4.1 on 2022-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0003_alter_feedback_tr_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="tr_number",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feedbackattachment",
            name="documentId",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="feedbackattachment",
            name="ers_file_name",
            field=models.TextField(),
        ),
    ]
