# Generated by Django 4.1 on 2022-08-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "publication_documents",
            "0007_rename_sentiment_map_publication_sentiment_map_png",
        ),
        ("feedbacks", "0004_alter_feedback_tr_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="publication_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to="publication_documents.publication",
            ),
        ),
    ]
