# Generated by Django 4.1 on 2022-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertype",
            name="include_in_sentiment_analysis",
            field=models.BooleanField(default=True),
        ),
    ]
