# Generated by Django 4.1 on 2022-08-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("committees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=25, unique=True)),
            ],
        ),
    ]
