# Generated by Django 4.1 on 2022-08-25 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("committees", "0001_initial"),
        ("policy_areas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalBasis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_legal", models.URLField()),
                ("article", models.CharField(blank=True, max_length=8, null=True)),
                ("paragraph", models.CharField(blank=True, max_length=8, null=True)),
                ("alinea", models.CharField(blank=True, max_length=8, null=True)),
                ("point", models.CharField(blank=True, max_length=8, null=True)),
                ("phrase", models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100)),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Initiative",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("created_date", models.DateTimeField()),
                ("dg", models.CharField(max_length=10)),
                ("dossier_summary", models.TextField(blank=True, null=True)),
                ("is_evaluation", models.BooleanField(blank=True, null=True)),
                ("is_grouped_cfe", models.BooleanField(blank=True, null=True)),
                ("is_major", models.BooleanField(blank=True, null=True)),
                ("modified_date", models.DateTimeField()),
                ("reference", models.CharField(max_length=100)),
                ("order_date", models.DateTimeField()),
                ("published_date", models.DateTimeField()),
                ("short_title", models.CharField(max_length=500)),
                (
                    "better_regulation_requirement",
                    models.ManyToManyField(to="categories.betterregulationrequirement"),
                ),
                (
                    "committee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committees.committee",
                    ),
                ),
                (
                    "expert_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="committees.expertgroup",
                    ),
                ),
                (
                    "foreseen_act_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.type",
                    ),
                ),
                (
                    "initiative_category",
                    models.ManyToManyField(to="categories.category"),
                ),
                (
                    "initiative_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="initiatives.status",
                    ),
                ),
                (
                    "legal_basis",
                    models.ManyToManyField(blank=True, to="initiatives.legalbasis"),
                ),
                ("policy_areas", models.ManyToManyField(to="policy_areas.policyarea")),
            ],
        ),
    ]
