# Generated by Django 4.1 on 2022-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalbasis",
            name="article",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
