# Generated by Django 4.1 on 2022-08-22 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0003_alter_initiative_initiative_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="initiative",
            name="receiving_feedback_status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiative_feedback_status",
                to="initiatives.status",
            ),
        ),
    ]
