# Generated by Django 4.1 on 2022-08-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("initiatives", "0003_alter_legalbasis_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalbasis",
            name="article",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
