# Generated by Django 4.1 on 2022-09-04 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NamedEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("salience", models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name="NamedEntityMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "named_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="named_entities.namedentity",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NamedEntityMentions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500)),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "named_entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="named_entities.namedentity",
                    ),
                ),
            ],
        ),
    ]
