# Generated by Django 4.1 on 2022-08-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("feedbacks", "0004_alter_feedback_tr_number_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive", models.DecimalField(decimal_places=3, max_digits=4)),
                ("neutral", models.DecimalField(decimal_places=3, max_digits=4)),
                ("negative", models.DecimalField(decimal_places=3, max_digits=4)),
                ("compound", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "feedback",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedbacks.feedback",
                    ),
                ),
            ],
        ),
    ]
