# Generated by Django 4.1 on 2022-08-26 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0004_alter_feedback_tr_number_and_more"),
        ("sentiments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sentiment",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sentiments",
                to="feedbacks.feedback",
            ),
        ),
    ]
